#include "Algolithm/BlasterBulletEnemyCollisionAlgolithm.h"
#include "Algolithm/BlasterBulletScarecrowCollisionAlgolithm.h"
#include "Algolithm/BoltPlayerCollisionAlgolithm.h"
#include "Algolithm/BombGloveBulletEnemyCollisionAlgolithm.h"
#include "Algolithm/BombGloveBulletScarecrowCollisionAlgolithm.h"
#include "Algolithm/BulletItemPlayerCollisionAlgolithm.h"

#include "Algolithm/EnemyBlasterBulletCollisionAlgolithm.h"
#include "Algolithm/EnemyBombGloveBulletCollisionAlgolithm.h"
#include "Algolithm/EnemyBombGloveEffectCollisionAlgolithm.h"
#include "Algolithm/EnemyEnemyCollisionAlgolithm.h"
#include "Algolithm/EnemyMeleeAttackPlayerCollisionAlgolithm.h"
#include "Algolithm/EnemyOmniWrenchCollisionAlgolithm.h"
#include "Algolithm/EnemyPlayerCollisionAlgolithm.h"
#include "Algolithm/EnemyPyrocitorBulletCollisionAlgolithm.h"

#include "Algolithm/NanotechItemPlayerCollisionAlgolithm.h"

#include "Algolithm/PlayerEnemyBulletCollisionAlgolithm.h"
#include "Algolithm/PlayerEnemyCollisionAlgolithm.h"
#include "Algolithm/PlayerEnemyMeleeAttackCollisionAlgolithm.h"
#include "Algolithm/PlayerKingCollisionAlgolithm.h"
#include "Algolithm/PlayerNanotechItemCollisionAlgolithm.h"
#include "Algolithm/PlayerQueenCollisionAlgolithm.h"
#include "Algolithm/PlayerScarecrowCollisionAlgolithm.h"
#include "Algolithm/PlayerShipCollisionAlgolithm.h"
#include "Algolithm/PlayerShopCollisionAlgolithm.h"
#include "Algolithm/PlayerWallCollisionAlgolithm.h"
#include "Algolithm/PlayerWaterFlowCollisionAlgolithm.h"


#include "Algolithm/ScarecrowBlasterBulletCollisionAlgolithm.h"
#include "Algolithm/ScarecrowBombGloveBulletCollisionAlgolithm.h"
#include "Algolithm/ScarecrowBombGloveEffectCollisionAlgolithm.h"
#include "Algolithm/ScarecrowOmniWrenchCollisionAlgolithm.h"
#include "Algolithm/ScarecrowPyrocitorBulletCollisionAlgolithm.h"

#include "Algolithm/ShipPlayerCollisionAlgolithm.h"
#include "Algolithm/SightEnemyCollisionAlgolithm.h"
#include "Algolithm/SightPlayerCollisionAlgolithm.h"